clean2:
	@$(file > clean, $(OBJS) $(C_DEPS) $(CPP_DEPS)) project_cleaner.exe  clean
	-$(RM) $(CC_DEPS) $(C++_DEPS) $(C_UPPER_DEPS) $(CXX_DEPS) $(SECONDARY_FLASH) $(SECONDARY_SIZE) $(ASM_DEPS) $(S_UPPER_DEPS) *.elf
	-@echo ' '

*.elf: $(wildcard ../linking_scripts/M55M1.ld)
