// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void ShowNVT_Animation(lv_obj_t * TargetObject, int delay);
void ShowRTT_Animation(lv_obj_t * TargetObject, int delay);
void ShowLVGL_Animation(lv_obj_t * TargetObject, int delay);
void ShowSLS_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_SystemInfo1;
extern lv_obj_t * ui_DATETIME1;
extern lv_obj_t * ui_TIMEZONE1;
extern lv_obj_t * ui_INTERFACE1;
extern lv_obj_t * ui_MACCADDR1;
extern lv_obj_t * ui_IPADDR1;
extern lv_obj_t * ui_NETMSK1;
extern lv_obj_t * ui_GWADDR1;
extern lv_obj_t * ui_DNS1;
extern lv_obj_t * ui_MQTTBROKER;
extern lv_obj_t * ui_MQTTCLIENTID;
extern lv_obj_t * ui_MQTTTOPIC;
extern lv_obj_t * ui_MQTTCONNECT;
extern lv_obj_t * ui_MQTTPUBLISH;
extern lv_obj_t * ui_SystemInfo;
extern lv_obj_t * ui_DATETIME;
extern lv_obj_t * ui_TIMEZONE;
extern lv_obj_t * ui_INTERFACE;
extern lv_obj_t * ui_MACCADDR;
extern lv_obj_t * ui_IPADDR;
extern lv_obj_t * ui_NETMSK;
extern lv_obj_t * ui_GWADDR;
extern lv_obj_t * ui_DNS;
extern lv_obj_t * ui_MQTTBROKER1;
extern lv_obj_t * ui_MQTTCLIENTID1;
extern lv_obj_t * ui_MQTTTOPIC1;
extern lv_obj_t * ui_MQTTCONNECT1;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_ImageLVGL;
extern lv_obj_t * ui_ImageRTT;
extern lv_obj_t * ui_ImageSLS;
extern lv_obj_t * ui_ImageNVT;
extern lv_obj_t * ui_ImageM55M1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_lvgl_png);    // assets/LVGL.png
LV_IMG_DECLARE(ui_img_rtt_png);    // assets/rtt.png
LV_IMG_DECLARE(ui_img_sls_png);    // assets/sls.png
LV_IMG_DECLARE(ui_img_nuvoton_logo_png);    // assets/nuvoton_logo.png
LV_IMG_DECLARE(ui_img_m55m1_png);    // assets/m55m1.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
