import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Nuvoton/M5531/Source/startup_M5531.c
Nuvoton/M5531/Source/system_M5531.c
""")

path = [cwd + '/Nuvoton/M5531/Include',]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
