import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Nuvoton/M55M1/Source/startup_M55M1.c
Nuvoton/M55M1/Source/system_M55M1.c
""")

path = [cwd + '/Nuvoton/M55M1/Include',]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
