// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SystemInfo1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_SystemInfo1, 172);
    lv_obj_set_height(ui_SystemInfo1, 356);
    lv_obj_set_x(ui_SystemInfo1, -614);
    lv_obj_set_y(ui_SystemInfo1, -4);
    lv_obj_set_align(ui_SystemInfo1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_SystemInfo1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SystemInfo1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_SystemInfo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_SystemInfo1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DATETIME1 = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_DATETIME1, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_DATETIME1, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_DATETIME1, -77);
    lv_obj_set_y(ui_DATETIME1, -84);
    lv_obj_set_align(ui_DATETIME1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DATETIME1, "DateTime");
    lv_obj_set_style_text_color(ui_DATETIME1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DATETIME1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DATETIME1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TIMEZONE1 = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_TIMEZONE1, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_TIMEZONE1, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_TIMEZONE1, -77);
    lv_obj_set_y(ui_TIMEZONE1, -84);
    lv_obj_set_align(ui_TIMEZONE1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TIMEZONE1, "TimeZone");
    lv_obj_set_style_text_color(ui_TIMEZONE1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TIMEZONE1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TIMEZONE1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_INTERFACE1 = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_INTERFACE1, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_INTERFACE1, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_INTERFACE1, -77);
    lv_obj_set_y(ui_INTERFACE1, -84);
    lv_obj_set_align(ui_INTERFACE1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_INTERFACE1, "Interface");
    lv_obj_set_style_text_color(ui_INTERFACE1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_INTERFACE1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_INTERFACE1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MACCADDR1 = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_MACCADDR1, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_MACCADDR1, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_x(ui_MACCADDR1, -75);
    lv_obj_set_y(ui_MACCADDR1, 43);
    lv_obj_set_align(ui_MACCADDR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MACCADDR1, "MAC Address");
    lv_obj_set_style_text_color(ui_MACCADDR1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MACCADDR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MACCADDR1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPADDR1 = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_IPADDR1, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_IPADDR1, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_IPADDR1, -77);
    lv_obj_set_y(ui_IPADDR1, -84);
    lv_obj_set_align(ui_IPADDR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPADDR1, "IP Address");
    lv_obj_set_style_text_color(ui_IPADDR1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPADDR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPADDR1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NETMSK1 = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_NETMSK1, LV_SIZE_CONTENT);   /// 102
    lv_obj_set_height(ui_NETMSK1, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_NETMSK1, -96);
    lv_obj_set_y(ui_NETMSK1, -50);
    lv_obj_set_align(ui_NETMSK1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NETMSK1, "Netmask");
    lv_obj_set_style_text_color(ui_NETMSK1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NETMSK1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NETMSK1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GWADDR1 = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_GWADDR1, LV_SIZE_CONTENT);   /// 88
    lv_obj_set_height(ui_GWADDR1, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_GWADDR1, 89);
    lv_obj_set_y(ui_GWADDR1, 71);
    lv_obj_set_align(ui_GWADDR1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GWADDR1, "Gateway");
    lv_obj_set_style_text_color(ui_GWADDR1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GWADDR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GWADDR1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DNS1 = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_DNS1, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_DNS1, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_DNS1, -97);
    lv_obj_set_y(ui_DNS1, 20);
    lv_obj_set_align(ui_DNS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DNS1, "DNS");
    lv_obj_set_style_text_color(ui_DNS1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DNS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DNS1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQTTBROKER = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_MQTTBROKER, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_MQTTBROKER, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_MQTTBROKER, -77);
    lv_obj_set_y(ui_MQTTBROKER, -91);
    lv_obj_set_align(ui_MQTTBROKER, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQTTBROKER, "MQTT Broker");
    lv_obj_set_style_text_color(ui_MQTTBROKER, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MQTTBROKER, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MQTTBROKER, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQTTCLIENTID = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_MQTTCLIENTID, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_MQTTCLIENTID, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_MQTTCLIENTID, -77);
    lv_obj_set_y(ui_MQTTCLIENTID, -84);
    lv_obj_set_align(ui_MQTTCLIENTID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQTTCLIENTID, "MQTT ClientID");
    lv_obj_set_style_text_color(ui_MQTTCLIENTID, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MQTTCLIENTID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MQTTCLIENTID, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQTTTOPIC = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_MQTTTOPIC, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_MQTTTOPIC, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_MQTTTOPIC, -74);
    lv_obj_set_y(ui_MQTTTOPIC, -79);
    lv_obj_set_align(ui_MQTTTOPIC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQTTTOPIC, "MQTT Topic");
    lv_obj_set_style_text_color(ui_MQTTTOPIC, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MQTTTOPIC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MQTTTOPIC, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQTTCONNECT = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_MQTTCONNECT, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_MQTTCONNECT, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_MQTTCONNECT, -77);
    lv_obj_set_y(ui_MQTTCONNECT, -84);
    lv_obj_set_align(ui_MQTTCONNECT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQTTCONNECT, "MQTT Status");
    lv_obj_set_style_text_color(ui_MQTTCONNECT, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MQTTCONNECT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MQTTCONNECT, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQTTPUBLISH = lv_label_create(ui_SystemInfo1);
    lv_obj_set_width(ui_MQTTPUBLISH, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_MQTTPUBLISH, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_MQTTPUBLISH, -77);
    lv_obj_set_y(ui_MQTTPUBLISH, -84);
    lv_obj_set_align(ui_MQTTPUBLISH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQTTPUBLISH, "Publish interval");
    lv_obj_set_style_text_color(ui_MQTTPUBLISH, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MQTTPUBLISH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MQTTPUBLISH, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SystemInfo = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_SystemInfo, 276);
    lv_obj_set_height(ui_SystemInfo, 356);
    lv_obj_set_x(ui_SystemInfo, -72);
    lv_obj_set_y(ui_SystemInfo, 58);
    lv_obj_set_align(ui_SystemInfo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SystemInfo, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SystemInfo, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_SystemInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DATETIME = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_DATETIME, 219);
    lv_obj_set_height(ui_DATETIME, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_DATETIME, -77);
    lv_obj_set_y(ui_DATETIME, -84);
    lv_obj_set_align(ui_DATETIME, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DATETIME, "2024-11-24 19:22:23");
    lv_obj_set_style_text_font(ui_DATETIME, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TIMEZONE = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_TIMEZONE, 191);
    lv_obj_set_height(ui_TIMEZONE, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_TIMEZONE, -77);
    lv_obj_set_y(ui_TIMEZONE, -84);
    lv_obj_set_align(ui_TIMEZONE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TIMEZONE, "UTC+8");
    lv_obj_set_style_text_font(ui_TIMEZONE, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_INTERFACE = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_INTERFACE, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_INTERFACE, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_INTERFACE, -77);
    lv_obj_set_y(ui_INTERFACE, -82);
    lv_obj_set_align(ui_INTERFACE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_INTERFACE, "e0");
    lv_obj_set_style_text_font(ui_INTERFACE, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MACCADDR = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_MACCADDR, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_MACCADDR, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_x(ui_MACCADDR, -75);
    lv_obj_set_y(ui_MACCADDR, 43);
    lv_obj_set_align(ui_MACCADDR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MACCADDR, "FF-FF-FF-FF-FF-FF");
    lv_obj_set_style_text_font(ui_MACCADDR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPADDR = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_IPADDR, 187);
    lv_obj_set_height(ui_IPADDR, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_IPADDR, -78);
    lv_obj_set_y(ui_IPADDR, -84);
    lv_obj_set_align(ui_IPADDR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPADDR, "0.0.0.0");
    lv_obj_set_style_text_font(ui_IPADDR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NETMSK = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_NETMSK, 206);
    lv_obj_set_height(ui_NETMSK, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_NETMSK, -98);
    lv_obj_set_y(ui_NETMSK, -50);
    lv_obj_set_align(ui_NETMSK, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NETMSK, "0.0.0.0");
    lv_obj_set_style_text_font(ui_NETMSK, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GWADDR = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_GWADDR, 198);
    lv_obj_set_height(ui_GWADDR, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_GWADDR, 50);
    lv_obj_set_y(ui_GWADDR, 85);
    lv_obj_set_align(ui_GWADDR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GWADDR, "0.0.0.0");
    lv_obj_set_style_text_font(ui_GWADDR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DNS = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_DNS, 205);
    lv_obj_set_height(ui_DNS, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_DNS, -97);
    lv_obj_set_y(ui_DNS, 20);
    lv_obj_set_align(ui_DNS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DNS, "0.0.0.0");
    lv_obj_set_style_text_font(ui_DNS, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQTTBROKER1 = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_MQTTBROKER1, LV_SIZE_CONTENT);   /// 101
    lv_obj_set_height(ui_MQTTBROKER1, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_MQTTBROKER1, -77);
    lv_obj_set_y(ui_MQTTBROKER1, -84);
    lv_obj_set_align(ui_MQTTBROKER1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQTTBROKER1, "mqtt.eclipseprojects.io:1883");
    lv_obj_set_style_text_font(ui_MQTTBROKER1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQTTCLIENTID1 = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_MQTTCLIENTID1, 197);
    lv_obj_set_height(ui_MQTTCLIENTID1, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_MQTTCLIENTID1, -76);
    lv_obj_set_y(ui_MQTTCLIENTID1, -84);
    lv_obj_set_align(ui_MQTTCLIENTID1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQTTCLIENTID1, "<client-id>");
    lv_obj_set_style_text_font(ui_MQTTCLIENTID1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQTTTOPIC1 = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_MQTTTOPIC1, 199);
    lv_obj_set_height(ui_MQTTTOPIC1, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_MQTTTOPIC1, -77);
    lv_obj_set_y(ui_MQTTTOPIC1, -84);
    lv_obj_set_align(ui_MQTTTOPIC1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQTTTOPIC1, "<client-id>/image");
    lv_obj_set_style_text_font(ui_MQTTTOPIC1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MQTTCONNECT1 = lv_label_create(ui_SystemInfo);
    lv_obj_set_width(ui_MQTTCONNECT1, 231);
    lv_obj_set_height(ui_MQTTCONNECT1, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_MQTTCONNECT1, -69);
    lv_obj_set_y(ui_MQTTCONNECT1, -82);
    lv_obj_set_align(ui_MQTTCONNECT1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MQTTCONNECT1, "non-connected");
    lv_obj_set_style_text_font(ui_MQTTCONNECT1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_SystemInfo);
    lv_slider_set_range(ui_Slider2, 100, 5000);
    lv_slider_set_value(ui_Slider2, 1000, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 227);
    lv_obj_set_height(ui_Slider2, 19);
    lv_obj_set_x(ui_Slider2, 2);
    lv_obj_set_y(ui_Slider2, 211);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider2,
                                                                                              lv_obj_get_style_pad_right(ui_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ImageLVGL = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_ImageLVGL, &ui_img_lvgl_png);
    lv_obj_set_width(ui_ImageLVGL, LV_SIZE_CONTENT);   /// 173
    lv_obj_set_height(ui_ImageLVGL, LV_SIZE_CONTENT);    /// 67
    lv_obj_set_x(ui_ImageLVGL, -222);
    lv_obj_set_y(ui_ImageLVGL, -174);
    lv_obj_set_align(ui_ImageLVGL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLVGL, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageLVGL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_ImageLVGL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageRTT = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_ImageRTT, &ui_img_rtt_png);
    lv_obj_set_width(ui_ImageRTT, LV_SIZE_CONTENT);   /// 182
    lv_obj_set_height(ui_ImageRTT, LV_SIZE_CONTENT);    /// 68
    lv_obj_set_x(ui_ImageRTT, -218);
    lv_obj_set_y(ui_ImageRTT, -173);
    lv_obj_set_align(ui_ImageRTT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageRTT, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageRTT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_ImageRTT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSLS = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_ImageSLS, &ui_img_sls_png);
    lv_obj_set_width(ui_ImageSLS, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_ImageSLS, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_ImageSLS, -222);
    lv_obj_set_y(ui_ImageSLS, -172);
    lv_obj_set_align(ui_ImageSLS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSLS, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageSLS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_ImageSLS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageNVT = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_ImageNVT, &ui_img_nuvoton_logo_png);
    lv_obj_set_width(ui_ImageNVT, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_ImageNVT, LV_SIZE_CONTENT);    /// 82
    lv_obj_set_x(ui_ImageNVT, -222);
    lv_obj_set_y(ui_ImageNVT, -174);
    lv_obj_set_align(ui_ImageNVT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageNVT, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageNVT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_ImageNVT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageM55M1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_ImageM55M1, &ui_img_m55m1_png);
    lv_obj_set_width(ui_ImageM55M1, LV_SIZE_CONTENT);   /// 104
    lv_obj_set_height(ui_ImageM55M1, LV_SIZE_CONTENT);    /// 106
    lv_obj_set_x(ui_ImageM55M1, 4);
    lv_obj_set_y(ui_ImageM55M1, -175);
    lv_obj_set_align(ui_ImageM55M1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageM55M1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageM55M1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
